### ISSUE TITLE
Auto increment field

### ISSUE THREAD

**Issue by Dartui** [DbDesigner/translations#30]
### First problem
When I add Auto Increment to field, next field also has Auto Increment option checked. 
![1](https://cloud.githubusercontent.com/assets/2657856/16618173/41f320ba-4388-11e6-9f04-12d5420a6258.jpg) ![2](https://cloud.githubusercontent.com/assets/2657856/16618172/41f2ff4a-4388-11e6-8c63-41ecebee7d31.jpg)
### Second problem
When I try to export schema to SQL, Auto Increment option is missing.
![3](https://cloud.githubusercontent.com/assets/2657856/16618171/41f2cd0e-4388-11e6-9ec8-b409d5899679.jpg)

**Comment by VisualBean** [comment]
The First thing I don't really find to be a problem, its nice that it keeps most of the settings across field creation.
The second thing is an issue though, I can also attest to, it not working.
