### ISSUE TITLE
Export to image

### ISSUE THREAD

**Issue by haucongle** [DbDesigner/translations#4]
I see menu Export has Image..
I click Image, there is a dialog appear
That dialog has just 4 zoom in, zoom out, reset, close buttons
How I export to image?

**Comment by haucongle** [comment]
I found solution!.
Right click and choose "open image in new tab"

**Comment by cenan** [comment]
Yes, that part needs some explanation text.

**Comment by cenan** [comment]
I have added an "Open in new tab" button
